name: Build jar(s) and publish release.

on:
  push:
    branches:
      - master
      - dev
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew --no-daemon -q clean jar shadowJar

      - name: Get the version
        id: version
        run: echo "VERSION=$(./gradlew -q projectVersion)" >> $GITHUB_ENV

      - name: Create release
        run: |
          FILES=$(ls build/libs/*.jar | tr '\n' ' ')
          PRERELEASE_FLAG=""
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
              PRERELEASE_FLAG="--prerelease --latest=false"
              gh release delete ${{ env.VERSION }} --yes || true
          fi
          gh release create $PRERELEASE_FLAG ${{ env.VERSION }} $FILES
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
